spring.application.name=CourseManagement
spring.datasource.url=jdbc:mysql://localhost:3306/Model4_1?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gi?i h?n kích th??c t?i ?a cho t?ng file ??n l? (Ví d?: 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Gi?i h?n t?ng kích th??c t?i ?a cho toàn b? Request d? li?u g?i lên (Ví d?: 50 Megabytes)
spring.servlet.multipart.max-request-size=50MB